version: '3'

networks:
  laravel:

services:
  nginx:
    image: nginx:stable
    ports:
      - ${APP_PORT:-8000}:80
    volumes:
      - .:/var/www/html:cached
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf:delegated
    depends_on:
      - php
      - mysql
    networks:
      - laravel

  mysql:
    image: mysql/mysql-server:8.0
    ports:
      - ${DB_PORT_LOCAL:-33060}:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'no'
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    networks:
      - laravel

  php:
    image: owow/laravel-php:8.2
    tty: true
    # Add an extra host to allow Linux systems to use `host.docker.internal`.
    extra_hosts:
      host.docker.internal: host-gateway
    environment:
      - COMPOSER_MEMORY_LIMIT=-1
    volumes:
      - .:/var/www/html:cached
    networks:
      - laravel
